server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/onehour_job?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

langchain4j.dashscope.api-key=sk-ws-H.PMHREMP.d4Tm.MEUCIF79LNLSz6rDZ4BhTk7ECDf767BhLv7Zvpu6XehhBTbkAiEAgHux7KPti4NT0dYBk4UgXCR0-RqmEIwhXHGfsHdMHE8
langchain4j.dashscope.chat.model-name=qwen3.8-max
langchain4j.dashscope.embedding.model-name=text-embedding-v2